vich_uploader:
    db_driver: orm
    mappings:
        produits_images:
            uri_prefix: /uploads/images/produits
            upload_destination: '%kernel.project_dir%/public/uploads/images/produits'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
